### ISSUE TITLE
时不时会出现：链接被拒绝的报错

### ISSUE THREAD

**Issue by hy215215** [Reasno/fastmongo#17]
时不时会出现：链接被拒绝的报错
`[WARNING] RemoteGoTask::__call failed, because unable to establish connection tcp://127.0.0.1:6001: Connection refused (111)
[ERROR] Spiral\Goridge\Exceptions\RelayException: unable to establish connection tcp://127.0.0.1:6001: Connection refused (111)(0) in phar:///www_home/modocenter-server_push/modocenter-push-v5.0.10.phar/vendor/hyperf/gotask/src/Relay/CoroutineSocketRelay.php:137
Stack trace:
#0 phar:///www_home/modocenter-server_push/modocenter-push-v5.0.10.phar/vendor/hyperf/gotask/src/Relay/SocketTransporter.php(35): Hyperf\GoTask\Relay\CoroutineSocketRelay->connect()
#1 phar:///www_home/modocenter-server_push/modocenter-push-v5.0.10.phar/vendor/spiral/goridge/src/RPC.php(48): Hyperf\GoTask\Relay\CoroutineSocketRelay->send()
#2 phar:///www_home/modocenter-server_push/modocenter-push-v5.0.10.phar/vendor/hyperf/gotask/src/IPC/SocketIPCSender.php(55): Spiral\Goridge\RPC->call()
#3 phar:///www_home/modocenter-server_push/modocenter-push-v5.0.10.phar/vendor/hyperf/gotask/src/GoTaskConnection.php(89): Hyperf\GoTask\IPC\SocketIPCSender->call()
#4 phar:///www_home/modocenter-server_push/modocenter-push-v5.0.10.phar/vendor/hyperf/gotask/src/GoTaskConnection.php(50): Hyperf\GoTask\GoTaskConnection->retry()
#5 phar:///www_home/modocenter-server_push/modocenter-push-v5.0.10.phar/vendor/hyperf/gotask/src/SocketGoTask.php(41): Hyperf\GoTask\GoTaskConnection->__call()
#6 phar:///www_home/modocenter-server_push/modocenter-push-v5.0.10.phar/vendor/hyperf/gotask/src/GoTaskProxy.php(39): Hyperf\GoTask\SocketGoTask->call()
#7 phar:///www_home/modocenter-server_push/modocenter-push-v5.0.10.phar/vendor/hyperf/gotask/src/MongoClient/MongoProxy.php(76): Hyperf\GoTask\GoTaskProxy->call()
#8 phar:///www_home/modocenter-server_push/modocenter-push-v5.0.10.phar/vendor/hyperf/gotask/src/MongoClient/Collection.php(84): Hyperf\GoTask\MongoClient\MongoProxy->find()
#9 phar:///www_home/modocenter-server_push/modocenter-push-v5.0.10.phar/app/Mongo/Base.php(64): Hyperf\GoTask\MongoClient\Collection->find()
#10 phar:///www_home/modocenter-server_push/modocenter-push-v5.0.10.phar/runtime/container/proxy/App_Process_CommonQueue.proxy.php(197): App\Mongo\Base->find()
#11 phar:///www_home/modocenter-server_push/modocenter-push-v5.0.10.phar/runtime/container/proxy/App_Process_CommonQueue.proxy.php(45): App\Process\CommonQueue->check_state()
#12 phar:///www_home/modocenter-server_push/modocenter-push-v5.0.10.phar/runtime/container/proxy/App_Process_CommunityQueue.proxy.php(56): App\Process\CommonQueue->handle()
#13 phar:///www_home/modocenter-server_push/modocenter-push-v5.0.10.phar/vendor/hyperf/process/src/AbstractProcess.php(134): App\Process\CommunityQueue->handle()
#14 {main}
`
php 版本信息
`PHP 7.4.24 (cli) (built: Oct  3 2021 19:22:29) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Yasd v0.3.9-alpha, Our Copyright, by codinghuang`

swoole 信息
`swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.0
Built => Oct 15 2021 14:01:04
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608`

**Comment by medeirosinacio** [comment]
related: https://github.com/Reasno/fastmongo/issues/2
